### ISSUE TITLE
FossHubURLProvider.py 

### ISSUE THREAD

**Issue by stefanj135** [autopkg/rustymyers-recipes#27]
Hey Rusty,

Can you help and take a look please, seems like the FossHubURLProvider.py is having an issue, little more information below. Im hoping it's not us.

`FossHubURLProvider: Projects JSON last updated: Tue, 27 Sep 2022 08:14:45 GMT
{'Output': {}}
URLDownloader
Use of undefined key in variable substitution: 'url'
{'Input': {'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
                                             'Mac OS X 10_8_3) '
                                             'AppleWebKit/536.28.10 (KHTML, '
                                             'like Gecko) Version/6.0.3 '
                                             'Safari/536.28.10'},
           'url': '%url%'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 177, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', '%url%', '--fail', '--output', '/srv/autopkg/Cache/uk.ac.ox.orchard.munki.Audacityox/downloads/tmpki5adw6i', '--header', 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10']' returned non-zero exit status 6.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 331, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 185, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 180, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', '%url%', '--fail', '--output', '/srv/autopkg/Cache/uk.ac.ox.orchard.munki.Audacityox/downloads/tmpki5adw6i', '--header', 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10']' returned non-zero exit status 6.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', '%url%', '--fail', '--output', '/srv/autopkg/Cache/uk.ac.ox.orchard.munki.Audacityox/downloads/tmpki5adw6i', '--header', 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10']' returned non-zero exit status 6.
Failed.
Receipt written to /srv/autopkg/Cache/uk.ac.ox.orchard.munki.Audacityox/receipts/Audacityox-receipt-20220927-093953.plist

The following recipes failed:
    Audacityox.munki
        Error in uk.ac.ox.orchard.munki.Audacityox: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', '%url%', '--fail', '--output', '/srv/autopkg/Cache/uk.ac.ox.orchard.munki.Audacityox/downloads/tmpki5adw6i', '--header', 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10']' returned non-zero exit status 6.
`

**Comment by rustymyers** [comment]
Do you have your IP whitelisted by Fosshub?

**Comment by rustymyers** [comment]
Actually, looks like there needs to be a space on the app_type:
Try an override with the app_type set to 'macOS DMG ' or  'macOS DMG for Apple silicon '
```
{'Input': {'app_name': 'Audacity', 'app_type': 'macOS DMG '}}
FossHubURLProvider: Checking json for: 'Audacity' & 'macOS DMG ' from https://university.fosshub.com/projects.json
```

**Comment by stefanj135** [comment]
Worked like a dream, thanks Rusty.
