### ISSUE TITLE
URL Downloader error - could not resolve host - failing with FossHubURLProvider.py 

### ISSUE THREAD

**Issue by stefanj135** [autopkg/rustymyers-recipes#28]
Hi Rusty,

Having a different issue this time with the FossHubURLProvider.py since Audacity was updated on the 27th Jan. 

autopkg run -vv Audacityox.munki
Processing Audacityox.munki...
WARNING: Audacityox.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
com.github.rustymyers.SharedProcessors/FossHubURLProvider
{'Input': {'app_name': 'Audacity', 'app_type': 'macOS DMG '}}
FossHubURLProvider: Checking json for: 'Audacity' & 'macOS DMG ' from https://university.fosshub.com/projects.json
FossHubURLProvider: Projects JSON last updated: Wed, 01 Feb 2023 07:03:22 GMT
{'Output': {}}
URLDownloader
Use of undefined key in variable substitution: 'url'
{'Input': {'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
                                             'Mac OS X 10_8_3) '
                                             'AppleWebKit/536.28.10 (KHTML, '
                                             'like Gecko) Version/6.0.3 '
                                             'Safari/536.28.10'},
           'url': '%url%'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: ERROR: (6) Could not resolve host: %url%

curl: (6) Could not resolve host: %url%

Failed.
Receipt written to /srv/autopkg/Cache/uk.ac.ox.orchard.munki.Audacityox/receipts/Audacityox-receipt-20230201-142551.plist

The following recipes failed:
    Audacityox.munki
        Error in uk.ac.ox.orchard.munki.Audacityox: Processor: URLDownloader: Error: curl: (6) Could not resolve host: %url%

**Comment by rustymyers** [comment]
Looks like fosshub fixed the app_type and removed the extra space. Updated recipe is working again.
Thanks
rusty
