### ISSUE TITLE
Rewrite Synfig recipes to require --pkg

### ISSUE THREAD

**Issue by homebysix** [autopkg/rustymyers-recipes#4]
The FossHub.com TOS now prohibits automatic downloading, which unfortunately includes AutoPkg. Tim Sutton recently [removed](https://github.com/autopkg/timsutton-recipes/commit/6d76c7ff3255639bc4d03209ce052f4d853f2d39) his Audacity download recipe in order to comply with the new terms, and I suspect your Synfig recipes may be similarly affected.

The next best thing is probably to require a `--pkg` switch as input. The changes made to Audacity.munki in the commit above could serve as a template for such a change.

**Comment by rustymyers** [comment]
Thanks for the heads up. I've contacted FossHub and received permission for an exception. I'm going to update the recipe to reflect this.
